# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00793bfa490452b6b262aba7e354a7a5e8f405902c71c99aedb645f1ed4ce058ae64ad43f760ce1d174b98f4c35328d9c20c75d41770a5d78d3be4b09806cd8a

test:
  secret_key_base: cd1bf0ce6c95a84723f8b2b56f490fdef00d32a7c0fec4037bb29e4a138d8712645878f6b45ce01ab0f2ce6c3d9d826d064ac0ac76e4ae50af4d78e5d1a65c82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
